### PR TITLE
ci: Add a slack notifier workflow

### PR DESCRIPTION
**Pull request by aborgna-q**
Add a workflow based on `slackapi/slack-github-action`, that lets us rate-limit messages sent to slack to avoid spamming.

### CODE REVIEW

**Comment by aborgna-q** [comment]
Working test run: https://github.com/CQCL/tket-json-rs/actions/runs/11516969832/job/32060744921?pr=84

**Comment by aborgna-q** [comment]
Marking as draft until I solve how to keep track of timeouts.
The current "file artifact" solution only works if this workflow is called on each parent workflow run.
Otherwise, `download-artifacts` will not find any files in the previous run so the rate limiting would be ignored.

**Comment by aborgna-q** [comment]
It should be working now. See https://github.com/CQCL/tket-json-rs/actions/runs/11520657348/job/32072548437?pr=84

**Review by cqc-alec — APPROVED** [review]
LGTM

**Pull request merged**
